#!/bin/bash

echo Dileep: hai subash, how are you
echo subash: hai dileep, i am fine what about you
echo dileep: I am also fine thank you, what are you doing now
echo subash: I am learning shell scripting, what about you
echo dileep: i am also learning shell scripting, but i am facing some issues in it 
echo subash: what issues you are facing i am also learning shell scripting, maybe I can be able to he lp you 
echo dileep: I am facing issues in variable declaration and usage, can you please he lp me in it  
echo subhash: yes sure, I can help you in it, what issues you are facing in variable declaration an d usage 