#!/bin/bash
ID=$(id -u)
if [ $ID -ne 0 ]
VALIDATION()
{
then
echo "ERROR:: please run this script with root accesws"
exit 1 # you can give other than 0
else
ehco "you are root user"

fi # fi means reverse of if, indicating condition end
}



