#!/bin/bash
ID=$(id -u)

VALIDATION()
{
    if [ $ID -ne 0 ]
then
echo "ERROR:: please run this script with root accesws"
exit 1 # you can give other than 0
else
ehco "you are root user"

fi # fi means reverse of if, indicating condition end
}
if [ $? -ne 0 ]
then 
echo "ERROR:: Installing MySQL is failed"
exit 1 # you can give other than 0
else
echo "Installing MySQL is SUCCESS"
yum install mysql -y
VALIDATION $?
yum install git -y
VALIDATION $?


