#!/bin/bash
ID=$(id -u)
validation()
{
    if [ $ID -ne 0 ] # command line argument $? is used to check the last command execution status, if it is 0 then it is success and if it is other than 0 then it is failed

then 
echo "ERROR:: please run this script with root accesws"
exit 1 # you can give other than 0
else 
echo "you are root user"
fi # fi means reverse of if, indicating condition end
}